#!/usr/bin/env node
/* build-index.js — one generated cross-reference for the whole listener lesson, so cross-checking a fact
 * is a lookup, not forensics (Paul, 07-24: "so we don't have to keep doing forensics").
 *
 * WHY THIS EXISTS.  A dozen scripts each re-derive the same maps from _data/msg.json and the includes —
 * code→statement, code→statement-index, sign→scrawl, pass→its stretch of the wire. Every investigation
 * ("where does §511 sit in the message?", "what quotes statement #482?", "which passes show this sign?")
 * rebuilds one of those by hand. This bakes them ONCE, from ground truth, into plans/listener_index.json.
 *
 * GROUND TRUTH IN, DERIVED OUT.  Inputs: _data/msg.json (the wire — the only truth) and _includes/listener/
 * *.html (the diary). Output is regenerable and gitignored (plans/ is gitignored + Jekyll-excluded), so it
 * never churns git and never reaches the built site. Do not hand-edit it; edit this and re-run.
 *
 *   node scripts/build-index.js         # writes plans/listener_index.json
 *
 * SCHEMA (plans/listener_index.json):
 *   statements : { "<seq>": "<source line>" }         # the wire spine, seq 1-based over code+gate statements
 *   byCode     : { "<wire code>": <seq> }             # reverse lookup used everywhere
 *   rows       : [ { file,line,pass,entry,title, kind, value, readback, codes[],indices[],sources[] } ]
 *                                                      # every wire-bearing element in the diary, in doc order
 *   passes     : [ { pass,file,entry,title, rows, kinds{}, idx{min,max,median}, codes[], signsShown[] } ]
 *   signs      : { "<sign>": { scrawl, shownIn:[pass…] } }   # every data-s sign, its scrawl, where shown
 *   coins      : [ { word, sign, file,line,pass } ]          # every coined token (.coin[data-sign])
 */
'use strict';
const fs = require('fs'), path = require('path');
const ROOT = path.resolve(__dirname, '..');
const scrawl = require(path.join(ROOT, '_data/sign_scrawl.json'));
/* The spine and the diary walk are `scripts/wire.js` — the same two derivations `build-spine.js`
   works from, so the cross-reference and the page's "whole run" panels cannot come to disagree
   about which statement a row names. */
const WIRE = require('./wire');
const { statements, byCode } = WIRE;

const scanned = WIRE.scanDiary();
const rows = scanned.rows.map(r => Object.assign({}, r,
  { sources: r.indices.map(x => (x == null ? null : statements[x])) }));
const signs = {};                       // sign -> {scrawl, shownIn:Set}
for (const [name, passes] of Object.entries(scanned.signs))
  signs[name] = { scrawl: scrawl[name] || null, shownIn: passes };
const coins = scanned.coins;

// --- per-pass rollups, ordered by pass ----------------------------------------------------------------
const median = a => { const s = [...a].sort((x, y) => x - y); return s.length ? s[Math.floor(s.length / 2)] : null; };
const byPass = new Map();
for (const r of rows) {
  if (r.pass == null) continue;
  const key = r.pass + '|' + r.file;
  const p = byPass.get(key) || { pass: r.pass, file: r.file, entry: r.entry, title: r.title,
    rows: 0, kinds: {}, _idx: [], codes: new Set(), signsShown: new Set() };
  p.rows++; p.kinds[r.kind] = (p.kinds[r.kind] || 0) + 1;
  if (!r.readback) for (const x of r.indices) if (x != null) p._idx.push(x);   // provenance ignores read-backs
  for (const c of r.codes) p.codes.add(c);
  if (!p.title && r.title) p.title = r.title;
  byPass.set(key, p);
}
// attach signsShown per pass
for (const [name, info] of Object.entries(signs)) for (const pass of info.shownIn)
  for (const p of byPass.values()) if (p.pass === pass) p.signsShown.add(name);

const passes = [...byPass.values()].sort((a, b) => a.pass - b.pass).map(p => ({
  pass: p.pass, file: p.file, entry: p.entry, title: p.title, rows: p.rows, kinds: p.kinds,
  idx: p._idx.length ? { min: Math.min(...p._idx), max: Math.max(...p._idx), median: median(p._idx) } : null,
  codes: [...p.codes], signsShown: [...p.signsShown].sort(),
}));

const signsOut = {};
for (const [name, info] of Object.entries(signs))
  signsOut[name] = { scrawl: info.scrawl, shownIn: [...info.shownIn].filter(x => x != null).sort((a, b) => a - b) };

const out = {
  _note: 'GENERATED by scripts/build-index.js — do not hand-edit; regenerate with `node scripts/build-index.js`.',
  _from: { wire: '_data/msg.json', diary: '_includes/listener/*.html' },
  statements, byCode, rows, passes, signs: signsOut, coins,
};
const dest = path.join(ROOT, 'plans/listener_index.json');
fs.mkdirSync(path.dirname(dest), { recursive: true });   // plans/ is gitignored: absent in a fresh clone
fs.writeFileSync(dest, JSON.stringify(out, null, 1));
console.log(`plans/listener_index.json: ${Object.keys(statements).length} statements, ${rows.length} wire rows, ` +
            `${passes.length} passes, ${Object.keys(signsOut).length} signs, ${coins.length} coins`);
