#!/usr/bin/env node
/* THE MARK INVENTORY — every span class the listener lesson uses to put a mark on the page, what it
   means, whose it is, and which gate covers it.  Written because working that out took repeated forensics
   (three separate times in one session), and because the classes NOT covered by a gate are exactly where a
   fabricated mark hides: `▮` hid in `.gl`, `⬥` hid in the renderer's own `.gl`, and nothing at all watches
   `.tk`/`.bit`/`.cup`.

   THE ONE DISTINCTION THAT MATTERS.  A **SIGN** is a named symbol the message transmits (it has an id on the
   wire and a scrawl in `_data/sign_scrawl.json`); it must render as that scrawl, or as her coined WORD — never
   as a shape of our own.  Everything else on this page is either the wire's **STRUCTURE** (its atoms: cups,
   bits, tones — rendered in a fixed house alphabet, which is a representation choice, not a claim about a
   sign), or the **KEEPER'S OWN** notation (marks she invents to hold what she has read), or plain **LABEL**
   text.  Only the SIGN row can leak; the others cannot, because they never claim to be something transmitted.

   Usage:
     node scripts/inventory-marks.js            print the table (and write plans/MARK_INVENTORY.md)
     node scripts/inventory-marks.js --check    fail if reality drifts from the declaration below  */
const fs = require('fs'), path = require('path');
const ROOT = path.resolve(__dirname, '..');
const DIR = path.join(ROOT, '_includes/listener');

/* class -> declaration.  `shapes` is the CLOSED inventory of literal glyphs allowed in that class;
   null means "free text" (words, not marks).  Drift against this is what --check reports. */
const INVENTORY = [
  { cls: 'gl sg',    kind: 'SIGN',      shapes: null,
    what: 'a transmitted sign. The literal inside is only a NO-JS FALLBACK — the renderer replaces it via mark() with the real scrawl, or her coined word once she has one. Never read the fallback as "the mark".',
    gate: 'audit-glyphs (coins are words) · audit-coins · audit-readback · prose-check' },
  { cls: 'coin gl w', kind: 'SIGN',     shapes: null,
    what: 'the coining span: the moment she cuts a WORD for a sign. Must contain letters — a word, never a shape (the founder\'s ◇/✳ broke this until 07-23).',
    gate: 'audit-glyphs check 1' },
  { cls: 'gl w',     kind: 'SIGN',      shapes: null,
    what: 'a coined word token in running prose/rows (rendered form of the above).', gate: 'prose-check' },

  { cls: 'gl',       kind: 'HERS',      shapes: ['◌','⬚','○','◔'], est: 'p288',
    what: 'lambda-slot marks, and NOTHING else. A bound name has no sign on the wire — it is a position in a maker — so a shape is the only option. Hollow because §288 is where she meets it: "a new mark takes a HOLLOW for a slot". (⌂ ⇌ ⟳ ▸ are not hers — see audit-glyphs.)',
    gate: 'audit-glyphs allow-list (source AND js/listener.js)' },
  { cls: 'tk',       kind: 'HERS',      shapes: ['●'], est: 'p214',
    what: 'her tally, cut at §214: one ● for each small cup holding a one. Generated by tally() in the renderer, five to a group.',
    gate: 'inventory-marks --check' },
  { cls: 'tk z',     kind: 'HERS',      shapes: ['◦'], est: 'p214',
    what: 'the closing empty cup that ends a unary run — "◦ for the empty one that ends the run" (§214).',
    gate: 'inventory-marks --check' },

  { cls: 'bit',      kind: 'STRUCTURE', shapes: ['▪','▫'],
    what: 'the wire\'s binary digits: ▪ one, ▫ none. House alphabet for an atom\'s number, not a sign.',
    gate: 'inventory-marks --check' },
  { cls: 'cup o',    kind: 'STRUCTURE', shapes: ['⟅'],  what: 'an atom that OPENS a cup.',  gate: 'inventory-marks --check' },
  { cls: 'cup c',    kind: 'STRUCTURE', shapes: ['⟆'],  what: 'an atom that CLOSES a cup.', gate: 'inventory-marks --check' },
  { cls: 'cup',      kind: 'STRUCTURE', shapes: ['⟅','⟆'], what: 'both cup marks in one span (a key/legend).', gate: 'inventory-marks --check' },
  { cls: 'tn',       kind: 'STRUCTURE', shapes: ['˩','˨','˦','˥'],
    what: 'the four wire symbols as tone-letters — the message exactly as it arrives, before any reading.',
    gate: 'inventory-marks --check' },
  { cls: 'tn t0',    kind: 'STRUCTURE', shapes: ['˩'], what: 'the lowest of the four wire symbols, shown alone in the tone key.', gate: 'inventory-marks --check' },
  { cls: 'tn t1',    kind: 'STRUCTURE', shapes: ['˨'], what: 'the second wire symbol, in the tone key.', gate: 'inventory-marks --check' },
  { cls: 'tn t2',    kind: 'STRUCTURE', shapes: ['˦'], what: 'the third wire symbol, in the tone key.', gate: 'inventory-marks --check' },
  { cls: 'tn t3',    kind: 'STRUCTURE', shapes: ['˥'], what: 'the highest wire symbol, in the tone key.', gate: 'inventory-marks --check' },
  { cls: 'stem',     kind: 'STRUCTURE', shapes: ['▵','◃'],
    what: 'a shared family-root, seen on the wire as part of a compound symbol.', gate: 'inventory-marks --check' },

  { cls: 'coin',     kind: 'LABEL',     shapes: null,
    what: 'a coining of a WORD FOR A THING IN HER WORLD, not for a sign — §267 "a label worn, not counted". No data-sign, so the renderer never substitutes it; it is prose emphasis.', gate: '—' },
  { cls: 'step',     kind: 'LABEL',     shapes: null,
    what: 'a narration word between rows ("becomes"). THE RIGHT HOME for a connector — WRITING_CHECKLIST §3 forbids styling one as a mark.', gate: '—' },
  { cls: 'lbl',      kind: 'LABEL',     shapes: null, what: 'row label in a peel/fragment widget.',   gate: '—' },
  { cls: 'say',      kind: 'LABEL',     shapes: null, what: 'her gloss beside a row.',                gate: '—' },
  { cls: 'peel-say', kind: 'LABEL',     shapes: null, what: 'the gloss on a peel row.',               gate: '—' },
  { cls: 'seekmap-say', kind: 'LABEL',  shapes: null, what: 'gloss in the seeker map.',               gate: '—' },
  { cls: 'val',      kind: 'LABEL',     shapes: null, what: 'a value shown in a control/table.',      gate: '—' },
  { cls: 'tu-k',     kind: 'LABEL',     shapes: null, what: '"Watch ended:"/"Watch begins:" keys in a taking-up record.', gate: 'audit-watch' },
];
const BY_CLS = Object.fromEntries(INVENTORY.map(r => [r.cls, r]));

// ---- scan reality -----------------------------------------------------------
const seen = {};                     // cls -> Map(text -> count)
for (const f of fs.readdirSync(DIR).filter(x => x.endsWith('.html'))) {
  const src = fs.readFileSync(path.join(DIR, f), 'utf8');
  for (const m of src.matchAll(/<span class="([a-z][a-z0-9 -]*)"([^>]*)>([^<]*)<\/span>/g)) {
    const cls = m[1].trim(), attrs = m[2], txt = m[3];
    if (!txt.trim()) continue;
    if (cls === 'gl' && /style=/.test(attrs)) continue;      // styled English labels in the circuit controls
    (seen[cls] = seen[cls] || new Map()).set(txt, (seen[cls]?.get(txt) || 0) + 1);
  }
}

const problems = [];
/* A mark may only be called HERS if the TEXT establishes it. Assertion is not evidence — "HERS" was a label
   that let unearned shapes sit beside earned ones until 07-23, and the renderer cited a §300 that never
   existed. So every HERS row must cite the pass that shows the reader what the mark means, and that pass must
   be real. A mark with no citation is slop by definition. */
{
  const arc = fs.readdirSync(DIR).filter(x => x.endsWith('.html'))
    .map(f => fs.readFileSync(path.join(DIR, f), 'utf8')).join('');
  for (const r of INVENTORY.filter(r => r.kind === 'HERS')) {
    if (!r.est) problems.push(`class "${r.cls}" is claimed as HERS with no establishment citation — cite the pass that shows the reader what it means, or it is not hers`);
    else if (!arc.includes(`id="${r.est}"`)) problems.push(`class "${r.cls}" cites ${r.est}, which is not a pass in the arc (this is how the phantom §300 survived)`);
  }
}
for (const cls of Object.keys(seen)) {
  const dec = BY_CLS[cls];
  if (!dec) { problems.push(`class "${cls}" is used but not in the inventory — declare what it is and whose it is`); continue; }
  if (dec.shapes === null) continue;
  for (const txt of seen[cls].keys())
    for (const ch of [...txt].filter(c => c.trim()))
      if (!dec.shapes.includes(ch))
        problems.push(`class "${cls}" contains ${ch}, which is not in its declared inventory [${dec.shapes.join(' ')}]`);
}

// ---- report -----------------------------------------------------------------
const count = cls => [...(seen[cls]?.values() || [])].reduce((a, b) => a + b, 0);
if (process.argv.includes('--check')) {
  if (problems.length) {
    console.log(`✗ ${problems.length} mark-inventory drift(s):`);
    problems.forEach(p => console.log('    ' + p));
    process.exit(1);
  }
  console.log(`✓ marks: ${INVENTORY.length} classes, all declared; no undeclared shape in any closed class`);
} else {
  const rows = INVENTORY.map(r =>
    `| \`.${r.cls}\` | ${r.kind} | ${r.shapes ? r.shapes.map(s => '`' + s + '`').join(' ') : '*(words)*'} | ${count(r.cls)} | ${r.what} | ${r.gate} |`);
  const md = `# MARK_INVENTORY.md — every mark on the page, and whose it is

**GENERATED by \`scripts/inventory-marks.js\` — do not hand-edit; edit the declaration in that script.**
\`node scripts/inventory-marks.js --check\` (verify.sh) fails if the page drifts from this.

The one distinction that matters: a **SIGN** is transmitted, so it must render as its real scrawl or her coined
word — never a shape of ours. **STRUCTURE** is the wire's own atoms in a fixed house alphabet. **HERS** are marks
a keeper invents to hold what she read. **LABEL** is plain text. Only SIGN can leak.

| class | kind | shapes | uses | what it is | gate |
|---|---|---|---|---|---|
${rows.join('\n')}

${problems.length ? '**DRIFT:**\n' + problems.map(p => '- ' + p).join('\n') : '_No drift: every class declared, every closed class within its inventory._'}
`;
  fs.writeFileSync(path.join(ROOT, 'plans/MARK_INVENTORY.md'), md);
  console.log(md);
}
