#!/usr/bin/env node
/* THE MARK INVENTORY — every span class the listener lesson uses to put a mark on the page, what it
   means, whose it is, and which gate covers it.  Written because working that out took repeated forensics
   (three separate times in one session), and because the classes NOT covered by a gate are exactly where a
   fabricated mark hides: `▮` hid in `.gl`, `⬥` hid in the renderer's own `.gl`, and nothing at all watches
   `.tk`/`.bit`/`.cup`.

   THE ONE DISTINCTION THAT MATTERS.  A **SIGN** is a named symbol the message transmits (it has an id on the
   wire and a scrawl in `_data/sign_scrawl.json`); it must render as that scrawl, or as her coined WORD — never
   as a shape of our own.  Everything else on this page is either the wire's **STRUCTURE** (its atoms: cups,
   bits, tones — rendered in a fixed house alphabet, which is a representation choice, not a claim about a
   sign), or the **KEEPER'S OWN** notation (marks she invents to hold what she has read), or plain **LABEL**
   text.  Only the SIGN row can leak; the others cannot, because they never claim to be something transmitted.

   Usage:
     node scripts/inventory-marks.js            print the table (and write plans/MARK_INVENTORY.md)
     node scripts/inventory-marks.js --check    fail if reality drifts from the declaration below  */
const fs = require('fs'), path = require('path');
const ROOT = path.resolve(__dirname, '..');
const DIR = path.join(ROOT, '_includes/listener');
const ORDER = require('./arc-order');   // reading order — an "established at" check is meaningless without it

/* class -> declaration.  `shapes` is the CLOSED inventory of literal glyphs allowed in that class;
   null means "free text" (words, not marks).  Drift against this is what --check reports. */
const INVENTORY = [
  { cls: 'gl sg',    kind: 'SIGN',      shapes: null,
    what: 'a transmitted sign. The literal inside is only a NO-JS FALLBACK — the renderer replaces it via mark() with the real scrawl, or her coined word once she has one. Never read the fallback as "the mark".',
    gate: 'audit-glyphs (coins are words) · audit-coins · audit-readback · prose-check' },
  { cls: 'coin gl w', kind: 'SIGN',     shapes: null,
    what: 'the coining span: the moment she cuts a WORD for a sign. Must contain letters — a word, never a shape (the founder\'s ◇/✳ broke this until 07-23).',
    gate: 'audit-glyphs check 1' },
  { cls: 'gl w',     kind: 'SIGN',      shapes: null,
    what: 'a coined word token in running prose/rows (rendered form of the above).', gate: 'prose-check' },

  /* THE LAMBDA-SLOT HOLLOWS ◌ ⬚ ○ ◔ WERE HERE AND ARE GONE (08-08). They stood in for a slot's name,
     and the entry justifying them rested on a claim that is false: a bound name is NOT absent from the
     wire. `x` is sign id 43, sent as the atom ▪⟅101011⟆, and its run appears literally in statement 362.
     So a hollow was never a rendering of an absence — it was a SUBSTITUTION, four shapes nobody sent
     standing where four signs did. The book's own rule settles it: a saying goes down in the notation
     that is standing when it arrives. A slot's name is a sign, so it is drawn as its scrawl, and the
     thing worth seeing — the same mark in the head and again in the body — is plainer that way, not
     less plain. §288 now says so, and Ona's §427 reads the head as the cup of names it is.
     There is deliberately NO `.gl` entry with shapes any more: a bare `.gl` carrying a shape is
     unaccounted for and the gate will fail on it, which is what should happen. */
  { cls: 'tk',       kind: 'HERS',      shapes: ['●'], est: 'p214',
    what: 'her tally, cut at §214: one ● for each small cup holding a one. Generated by tally() in the renderer, five to a group.',
    gate: 'inventory-marks --check' },
  { cls: 'tk z',     kind: 'HERS',      shapes: ['◦'], est: 'p214',
    what: 'the closing empty cup that ends a unary run — "◦ for the empty one that ends the run" (§214).',
    gate: 'inventory-marks --check' },

  /* THE EMPTIES. Not a third construct: an atom is a type tag and a cup, and these are that same pair of
     atoms with NOTHING IN THE CUP (▫⟅⟆ a number with nothing in it, ▪⟅⟆ a name with nothing in it). They are
     told apart by reach, and the message settles it: ▫⟅⟆ is in tail position 3289/3289, so it runs to the end
     of its enclosure; ▪⟅⟆ is followed by a sibling 1220 times, so it takes exactly the one name behind it.
     Hollow for the hollow tag, filled for the filled one — the same run as ▪/▫ and ●/◦, so the page shows the
     one bit the wire uses. An ABBREVIATION, not a reading: three marks stand behind each and are written
     above, so it can be undone, which is why she may take it without knowing what either one means. */
  { cls: 'nil',      kind: 'HERS',      shapes: ['◇'], est: 'p246',
    what: 'the empty NUMBER-cup ▫⟅⟆, in one mark. Runs to the end of its enclosure — everything behind it goes together, with no cup shut round it. Ren cuts it at §246, NOT at §232 where she takes `tally` apart: the empty cup is the half that did not come that night, and a keeper does not invent a shorthand for something she is not writing. It first stands on her page alone at §239 and is on every line at §246, which is what earns it.',
    gate: 'inventory-marks --check' },
  { cls: 'nil w',    kind: 'HERS',      shapes: null, est: 'p214',
    what: 'the FOUNDER\'S MERGED MARK `tally`: one word for `▫⟅⟆ ▪⟅▪▪▪⟆` together. By §214 she has heard eighteen statements, sixteen carry the empty cup, and in all sixteen it stands immediately before the long run — she has never seen either alone, so the reading her evidence supports is that they are one thing. She is wrong. It comes apart at §232 on the first count that arrives with no empty cup in front of it; the long run keeps `tal`, her word short by the piece that did not come. Free text — a word, not a shape.',
    gate: 'inventory-marks --check' },
  /* est WAS p214 AND THAT WAS FALSE (fixed 08-08). ◆ renders nowhere in Maren's watch and could not:
     she never meets `▪⟅⟆` at all — her copied statements are `intro X` and `is:int | unary N`, and
     neither contains one. It arrives with the makers at §288, where Iso argues it from the shape Ren
     cut and the bit the message sends. The old citation passed the gate because the gate only asked
     whether p214 exists. It now checks that nothing renders before the pass it cites. */
  { cls: 'nil n',    kind: 'HERS',      shapes: ['◆'], est: 'p288',
    what: 'the empty NAME-cup ▪⟅⟆, in one mark. Reaches over exactly the one name behind it — which is also what tells a lambda\'s slot standing in the head from a USE of it down in the body (the sign alone in the head, ◆ before the sign in the body).',
    gate: 'inventory-marks --check' },

  /* Ren's cut ledger (§239) and what it grows into. A keeper's OWN bookkeeping notation: it never claims to
     be anything transmitted, which is why it cannot leak. It is also the book's one heirloom — Vess keeps it
     through the famine when she has no hand for prose, and Ona walks to the front of the book to read the key
     at §458. See plans/LISTENER_CHARACTERS.md §7. */
  { cls: 'key',      kind: 'HERS',      shapes: null, est: 'p239',
    what: 'the translation key Ren cuts at the front of the book so her shorthand survives her: r read and worked, c copied and not worked, b blank.',
    gate: 'inventory-marks --check' },
  { cls: 'tally-row', kind: 'HERS',     shapes: null, est: 'p239', el: 'span',
    what: 'one line of that ledger: pass, the mark it was about, then the counts. Free text — words and numbers, never a mark. It was `row` until 08-09, which was also the class of a generated message row — the exact opposite thing, the wire\'s marks rather than a keeper\'s figures about them. They were told apart by their element and nothing else, and a page-wide sweep duly got it wrong: the numeral pass skipped every ledger line as if it were the renderer\'s output. The `el` field stays because it is cheap and true, not because anything now depends on it.',
    gate: 'inventory-marks --check' },
  { cls: 'beat',     kind: 'HERS',      shapes: null, est: 'p587',
    what: 'Lio\'s §587 table: whether a beat came on this line, in her words ("a beat" / "no beat"). Free text. The `.none` modifier is the absent case, dimmed.',
    gate: 'inventory-marks --check' },
  { cls: 'beat none', kind: 'HERS',     shapes: null, est: 'p587',
    what: 'the no-beat case of `.beat`, same column, dimmed. Free text.',
    gate: 'inventory-marks --check' },
  { cls: 'keeps',    kind: 'HERS',      shapes: null, est: 'p587',
    what: 'Lio\'s §587 table: her verb for what the part then does with what it was told. Free text, never a mark.',
    gate: 'inventory-marks --check' },
  { cls: 'does',     kind: 'HERS',      shapes: null, est: 'p605',
    what: 'Lio\'s ledger, middle column: what one engine-order DOES, in her words. Free text, never a mark.',
    gate: 'inventory-marks --check' },
  { cls: 'trace',    kind: 'HERS',      shapes: ['\u25aa','\u25ab',' '], est: 'p605',
    what: 'Lio\'s ledger, right column: the trace of values that order left when she ran it. Her reading of a real run, so bits only.',
    gate: 'inventory-marks --check' },
  { cls: 'gap',      kind: 'HERS',      shapes: [], est: 'p388',
    what: 'Vess\'s ruled blank: a ledger column she cannot fill, ruled to the WIDTH of the thing that is missing and left empty. EMPTY inventory on purpose: the blank is drawn by a rule in CSS, not by characters, so the moment ANY shape appears in here it is claiming to be the lost mark, which is exactly the fabrication this file exists to stop. It used to hold ( · ) as a stand-in for the rule, and a reader could not tell what it meant (Paul, 08-01).',
    gate: 'inventory-marks --check' },

  { cls: 'bit',      kind: 'STRUCTURE', shapes: ['▪','▫'],
    what: 'the wire\'s binary digits: ▪ one, ▫ none. House alphabet for an atom\'s number, not a sign.',
    gate: 'inventory-marks --check' },
  { cls: 'fj',       kind: 'STRUCTURE', shapes: ['·'],
    what: 'the JOIN inside a compound sign. Maren cuts it at §221 — "Where two runs stand together like that I am putting a point between them, so nobody reads the pair as one long run." The renderer emits it for any `:`-compound; a hand row drawing a compound out uses the same mark.',
    gate: 'inventory-marks --check' },
  { cls: 'cup o',    kind: 'STRUCTURE', shapes: ['⟅'],  what: 'an atom that OPENS a cup.',  gate: 'inventory-marks --check' },
  { cls: 'cup c',    kind: 'STRUCTURE', shapes: ['⟆'],  what: 'an atom that CLOSES a cup.', gate: 'inventory-marks --check' },
  { cls: 'cup lo',   kind: 'STRUCTURE', shapes: ['⟦'],  what: 'opens a LIST (listener.js:79, `vector`). Renderer-generated, so it was invisible to this inventory until §501 hand-drew Senn\'s own table in the same shape (08-01).', gate: 'inventory-marks --check' },
  { cls: 'cup lc',   kind: 'STRUCTURE', shapes: ['⟧'],  what: 'closes a LIST. Same note as `cup lo`.', gate: 'inventory-marks --check' },
  { cls: 'lst o',    kind: 'STRUCTURE', shapes: ['᚛'],  what: 'opens a STRUNG ROW (listener.js, `(list N) …`). HERS, not the sender\'s: the wire sends a mark and a count of how many follow, and Bram drops the count and walls both ends instead, so she can feel where a row stops. Declared 08-06 when §372 first drew the pair by hand to introduce it.', gate: 'inventory-marks --check' },
  { cls: 'lst c',    kind: 'STRUCTURE', shapes: ['᚜'],  what: 'closes a strung row. Same note as `lst o`.', gate: 'inventory-marks --check' },
  { cls: 'cup',      kind: 'STRUCTURE', shapes: ['⟅','⟆'], what: 'both cup marks in one span (a key/legend).', gate: 'inventory-marks --check' },
  { cls: 'tn',       kind: 'STRUCTURE', shapes: ['˩','˨','˦','˥'],
    what: 'the four wire symbols as tone-letters — the message exactly as it arrives, before any reading.',
    gate: 'inventory-marks --check' },
  { cls: 'tn t0',    kind: 'STRUCTURE', shapes: ['˩'], what: 'the lowest of the four wire symbols, shown alone in the tone key.', gate: 'inventory-marks --check' },
  { cls: 'tn t1',    kind: 'STRUCTURE', shapes: ['˨'], what: 'the second wire symbol, in the tone key.', gate: 'inventory-marks --check' },
  { cls: 'tn t2',    kind: 'STRUCTURE', shapes: ['˦'], what: 'the third wire symbol, in the tone key.', gate: 'inventory-marks --check' },
  { cls: 'tn t3',    kind: 'STRUCTURE', shapes: ['˥'], what: 'the highest wire symbol, in the tone key.', gate: 'inventory-marks --check' },
  /* `stem` REMOVED 08-01. It declared ▵ and ◃ as "a shared family-root seen on the wire" — but ▵ was
     never used at all, and ◃ appeared exactly once (§501) standing in for the stem of the tape family,
     which the wire actually sends as a real two-glyph sign. A blind reader caught it: "the stem in the
     prose is drawn ◃ and nothing resembling ◃ appears in either line." That is the T8 fabrication class
     surviving by being filed under STRUCTURE instead of as a sign. The prose now points at the real
     `tape` sign, and `audit-signs` verifies the figure beside it shows that sign. */

  { cls: 'coin',     kind: 'LABEL',     shapes: null,
    what: 'a coining of a WORD FOR A THING IN HER WORLD, not for a sign — §267 "a label worn, not counted". No data-sign, so the renderer never substitutes it; it is prose emphasis.', gate: '—' },
  { cls: 'step',     kind: 'LABEL',     shapes: null,
    what: 'a narration word between rows ("becomes"). THE RIGHT HOME for a connector — WRITING_CHECKLIST §3 forbids styling one as a mark.', gate: '—' },
  { cls: 'lbl',      kind: 'LABEL',     shapes: null, what: 'row label in a peel/fragment widget.',   gate: '—' },
  { cls: 'say',      kind: 'LABEL',     shapes: null, what: 'her gloss beside a row.',                gate: '—' },
  { cls: 'peel-say', kind: 'LABEL',     shapes: null, what: 'the gloss on a peel row.',               gate: '—' },
  { cls: 'seekmap-say', kind: 'LABEL',  shapes: null, what: 'gloss in the seeker map.',               gate: '—' },
  { cls: 'val',      kind: 'LABEL',     shapes: null, what: 'a value shown in a control/table.',      gate: '—' },
  { cls: 'tu-k',     kind: 'LABEL',     shapes: null, what: '"Watch ended:"/"Watch begins:" keys in a taking-up record.', gate: 'audit-watch' },
  { cls: 'pf-k',     kind: 'LABEL',     shapes: null,
    what: 'a field key in the head of a pass — ON WATCH, SKY-SOUND. Same job as tu-k one level down: the taking-up is a station form filled at a handoff, this is the form a keeper fills at the top of a night.', gate: '—' },
  { cls: 'ln',       kind: 'LABEL',     shapes: null,
    what: 'one line of a block that is LINES rather than prose — a letter quoted into Cael\'s watch in the other hand\'s own cadence, or an item on Tamsin\'s bench list. Plain text, never a mark.', gate: '—' },
  { cls: 'sig',      kind: 'LABEL',     shapes: null,
    what: 'who signed that letter. An initial, because both correspondents sign that way and one of them has been dead three hundred passes.', gate: '—' },
  { cls: 'k',        kind: 'LABEL',     shapes: null,
    what: 'the field name in Neru\'s gauge line ("Vine") — the instrument reading she rules at the head of every entry from §310. A key, like tu-k, not a mark.', gate: '—' },
  { cls: 'hand',     kind: 'LABEL',     shapes: null,
    what: 'the other half of that gauge: WHOSE hands read it. Plain text, and the whole point of the field — read down her column and the answer stops being "mine".', gate: '—' },
];
const BY_CLS = Object.fromEntries(INVENTORY.map(r => [r.cls, r]));

// ---- scan reality -----------------------------------------------------------
const seen = {};                     // cls -> Map(text -> count)
for (const f of fs.readdirSync(DIR).filter(x => x.endsWith('.html'))) {
  const src = fs.readFileSync(path.join(DIR, f), 'utf8');
  for (const m of src.matchAll(/<span class="([a-z][a-z0-9 -]*)"([^>]*)>([^<]*)<\/span>/g)) {
    const cls = m[1].trim(), attrs = m[2], txt = m[3];
    if (!txt.trim()) continue;
    if (cls === 'gl' && /style=/.test(attrs)) continue;      // styled English labels in the circuit controls
    (seen[cls] = seen[cls] || new Map()).set(txt, (seen[cls]?.get(txt) || 0) + 1);
  }
}

const problems = [];
/* A mark may only be called HERS if the TEXT establishes it. Assertion is not evidence — "HERS" was a label
   that let unearned shapes sit beside earned ones until 07-23, and the renderer cited a §300 that never
   existed. So every HERS row must cite the pass that shows the reader what the mark means, and that pass must
   be real. A mark with no citation is slop by definition.
   ★ AND THE CITATION MUST BE TRUE, checked 08-08. Until then this only asked whether the cited pass EXISTS,
   which `.nil n` (◆) exploited for months: it cited p214, Maren's watch, where ◆ appears nowhere and cannot
   — Maren never met `▪⟅⟆` at all. Iso cuts it at §288 and the entry says so in her own words. An existence
   check cannot catch a citation that names the wrong real pass, so it now checks that the mark does not
   RENDER before the pass that claims to introduce it. That is the whole content of "established": the reader
   met it here first. */
{
  const files = fs.readdirSync(DIR).filter(x => x.endsWith('.html'));
  const arc = ORDER.map(k => fs.readFileSync(path.join(DIR, k + '.html'), 'utf8')).join('');
  const passAt = [...arc.matchAll(/id="(p\d+)"/g)].map(m => [m.index, m[1]]);
  const passOf = i => { let cur = null; for (const [pos, id] of passAt) { if (pos <= i) cur = id; else break; } return cur; };
  for (const r of INVENTORY.filter(r => r.kind === 'HERS')) {
    if (!r.est) { problems.push(`class "${r.cls}" is claimed as HERS with no establishment citation — cite the pass that shows the reader what it means, or it is not hers`); continue; }
    if (!arc.includes(`id="${r.est}"`)) { problems.push(`class "${r.cls}" cites ${r.est}, which is not a pass in the arc (this is how the phantom §300 survived)`); continue; }
    /* Scoped by ELEMENT where an entry asks for it. This was load-bearing while `row` named two
       different things; since the ledger line became `tally-row` (08-09) it is only a tightening. */
    const tag = r.el || '[a-z]+';
    const re = new RegExp(`<${tag}\\s+class="${r.cls.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}"`, 'g');
    const first = [...arc.matchAll(re)][0];
    if (!first) continue;                       // never rendered; the shapes check covers that separately
    const at = passOf(first.index);
    if (at && at !== r.est)
      problems.push(`class "${r.cls}" cites ${r.est} as where it is established, but it first renders at ${at} — cite where the reader actually meets it`);
  }
}
for (const cls of Object.keys(seen)) {
  const dec = BY_CLS[cls];
  if (!dec) { problems.push(`class "${cls}" is used but not in the inventory — declare what it is and whose it is`); continue; }
  if (dec.shapes === null) continue;
  for (const txt of seen[cls].keys())
    for (const ch of [...txt].filter(c => c.trim()))
      if (!dec.shapes.includes(ch))
        problems.push(`class "${cls}" contains ${ch}, which is not in its declared inventory [${dec.shapes.join(' ')}]`);
}

// ---- report -----------------------------------------------------------------
const count = cls => [...(seen[cls]?.values() || [])].reduce((a, b) => a + b, 0);
if (process.argv.includes('--check')) {
  if (problems.length) {
    console.log(`✗ ${problems.length} mark-inventory drift(s):`);
    problems.forEach(p => console.log('    ' + p));
    process.exit(1);
  }
  console.log(`✓ marks: ${INVENTORY.length} classes, all declared; no undeclared shape in any closed class`);
} else {
  const rows = INVENTORY.map(r =>
    `| \`.${r.cls}\` | ${r.kind} | ${r.shapes ? r.shapes.map(s => '`' + s + '`').join(' ') : '*(words)*'} | ${count(r.cls)} | ${r.what} | ${r.gate} |`);
  const md = `# MARK_INVENTORY.md — every mark on the page, and whose it is

**GENERATED by \`scripts/inventory-marks.js\` — do not hand-edit; edit the declaration in that script.**
\`node scripts/inventory-marks.js --check\` (verify.sh) fails if the page drifts from this.

The one distinction that matters: a **SIGN** is transmitted, so it must render as its real scrawl or her coined
word — never a shape of ours. **STRUCTURE** is the wire's own atoms in a fixed house alphabet. **HERS** are marks
a keeper invents to hold what she read. **LABEL** is plain text. Only SIGN can leak.

| class | kind | shapes | uses | what it is | gate |
|---|---|---|---|---|---|
${rows.join('\n')}

${problems.length ? '**DRIFT:**\n' + problems.map(p => '- ' + p).join('\n') : '_No drift: every class declared, every closed class within its inventory._'}
`;
  fs.writeFileSync(path.join(ROOT, 'plans/MARK_INVENTORY.md'), md);
  console.log(md);
}
